# Generated by Django 5.2.5 on 2025-09-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'credentials"."log',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Open', max_length=20)),
            ],
            options={
                'db_table': 'credemtials"."supportticket',
            },
        ),
    ]
