# Generated by Django 5.2.5 on 2025-09-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_log_supportticket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supportticket',
            table='credentials"."supportticket',
        ),
    ]
